repository:
  name: expo-diff-purge
  description: "Documenting `expo init` changes from each SDK to the next. :rocket:"
  homepage: https://react-native-community.github.io/upgrade-helperaaaaa
  topics: expo, react-native, upgrade, purge, rn-diff, rn-diff-purge, upgrade-helper

  has_wiki: false
